### ISSUE TITLE
Parent layer inheritance

### ISSUE THREAD

**Issue by h2non** [vinxi/layer#10]
This is mostly a proposal. I've been using and implementing hierarchical middleware layers in multiple languages and in most of them I've supported the hierarchical inheritance support.

Essentially, this means that a middleware layer can have a parent layer, which implicitly inherits its behavior. It also has the benefit of a hierarchical error handling.

This is particularly useful when using it in nested entities structures, such as a router (indeed, I was missing it while implementing the `router` package right now).

This can be easily achieved here, as opcional feature, such as:

``` go
parent := New()
parent.Use(func (w http.ResponseWriter, r *http.Request, h http.Handler) {
  // parent middleware handler will be always executed
  h.ServeHTTP(w, r)
})

child := New()
parent.Use(func (w http.ResponseWriter, r *http.Request, h http.Handler) {
  // child will be executed too
  h.ServeHTTP(w, r)
})

// Set the parent layer
child.SetParent(parent)

// Run it (both middleware handler will be triggered)
child.Run("request", w, r, nil)
```

Opinions? @vinxi/core

**Comment by groyoh** [comment]
Yeah I can see the use case for that. When running the child middleware, at which point parent one will be called? Before the child one is called?

**Comment by h2non** [comment]
Will be called first, the code would look like:

``` go
func (l *Layer) Run(phase, w, r, h) {
  if l.Parent != nil {
    l.Parent.Run(phase, w, r, func (w, r) { 
      l.run(phase, w, r, h) // child run
    })
    return
  }

  l.run(phase, w, r) // run current scope only
}
```

**Comment by h2non** [comment]
In case of `error` phase, perhaps makes more sense to execute the child stack first, as opposite, since the natural thinking would be to attach very specific handlers for scoped layers, and if I don't have them, just use the parent generic handlers.

**Comment by h2non** [comment]
Feature supported. BTW just discovered one strange behavior in Go when using multiple panic recovery in the same stack call chain. Seems like Go only triggers one of them. I've to dig in detail into this and isolate an use case because the current behavior is so weird.

**Comment by h2non** [comment]
This feature is now supported and already used by `layer` package consumers. Closing.
