### ISSUE TITLE
Coverage reported to vinci-proxy

### ISSUE THREAD

**Issue by groyoh** [vinxi/layer#11]
After the name change, the coverage report of the existing projects seems to still report to vinci-proxy account on Coveralls e.g. https://coveralls.io/jobs/13378270.

**Comment by groyoh** [comment]
Found this https://github.com/lemurheavy/coveralls-public/issues/399 but couldn't find the mentioned button.

**Comment by h2non** [comment]
Seems like something is leaking in Coveralls. Other repos has been migrated properly. Will take a look.

**Comment by h2non** [comment]
I've removed and added the repository in Coveralls and TravisCI. Let's see if it works now.

**Comment by h2non** [comment]
Fixed. See: https://coveralls.io/github/vinxi/layer?branch=feat%2Finheritance

**Comment by groyoh** [comment]
![yojc2gnsclbpokv0ea](https://cloud.githubusercontent.com/assets/7434196/14397969/ddf7358e-fde0-11e5-8545-64f84a5a8ef7.gif)

**Comment by h2non** [comment]
LOL

Seems like we have now the same trouble with [replay](https://github.com/vinxi/replay).

**Comment by groyoh** [comment]
Did you actually report it to coveralls?

**Comment by h2non** [comment]
Not yet.
