### ISSUE TITLE
Consider using a priority queue

### ISSUE THREAD

**Issue by h2non** [vinxi/layer#13]
Instead of current stack sliced implementation.

**Comment by h2non** [comment]
@groyoh what do you think?

**Comment by groyoh** [comment]
@h2non what is exactly the idea here? Allowing any kind of priority (e.g. a number) for the layer? Or would it be the same behavior but with a different data structure?

**Comment by h2non** [comment]
I guess the same hehavior but with a diferent data structure approach.

**Comment by h2non** [comment]
Deprecated for now. Closing.
