### ISSUE TITLE
Memoize stack chain

### ISSUE THREAD

**Issue by h2non** [vinxi/layer#8]

**Comment by h2non** [comment]
Done!

**Comment by groyoh** [comment]
That also means that once a `phase` runs for the first time it will not be possible to change it afterward, right?

**Comment by h2non** [comment]
Everytime the phase-specific middleware stack mutates (a new handler is added) the memoized function will be automatically flushed, therefore there's no constrains in this sense, you can attach new handler whenever you want.

Also, I've done some bench tests and the benefit or doing memorization at this level seems to be really low (just a reduced set of nanoseconds of less computation), so we could remove this if after more tests in real use cases we don't have any significant benefit.

**Comment by groyoh** [comment]
Oh I missed the "flush" part I guess. Sounds good to me :+1:
